version: "3.8"

services:
  webapp:
    build:
      context: ./webapp
    container_name: webapp
    expose:
      - 5000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=usuario
      - DB_PASSWORD=clave123
      - DB_NAME=webappdb

  apache:
    build:
      context: ./apache-proxy
      args:
        - APACHE_CONF=${APACHE_CONF:-apache-dev.conf}
    container_name: apache-ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: webappdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

volumes:
  mysql-data:
